import { DealerCar } from '../types/dealerCar';

export const tenantTheme = {
  name: "Enuel Motors Zambia",
  logoUrl: "/mock-logo.png",
  primaryColor: "#0F3D91",
  accentColor: "#F4C430",
  country: "Zambia",
  baseCurrency: "ZMW" as const,
  phone: "+260 97 000 0000",
  whatsapp: "+260970000000",
  email: "sales@enuelmotors.com",
  location: "Lusaka, Zambia",
  contactInfo: {
    address: 'Lusaka, Zambia',
    phone: '+260 97 000 0000',
    whatsapp: '+260970000000',
    email: 'sales@enuelmotors.com',
  },
  heroTitle: "Japanese Used Cars - Direct Import",
  heroSubtitle: "Quality pre-owned vehicles from trusted Japanese auctions with full export documentation",
  brandTone: "professional" as const,
  sections: {
    showHowToBuy: true,
    showWhyChooseUs: true,
    showTestimonials: true,
  },
  listing: {
    defaultView: "grid" as const,
    showPrices: true,
  },
  export: { enabled: false },
  backgroundColor: '#ffffff',
};

export const cars: DealerCar[] = [
  {
    id: "1",
    stockNo: "DJ-8891",
    make: "Toyota",
    model: "Harrier",
    grade: "Premium",
    year: 2017,
    mileage_km: 86000,
    engine_cc: 2500,
    transmission: "AT",
    fuel: "Petrol",
    steering: "RHD",
    price_usd: 10500,
    price_local_zmw: 220000,
    currency: "USD",
    location: "Lusaka Yard",
    bodyType: "SUV",
    color: "White",
    images: ["/cars/car-1.jpg", "/cars/car-1-2.jpg"],
    status: "Available",
    vin: "JH4DC...1",
    inspectionReportUrl: '/inspection-reports/1.pdf',
  },
  {
    id: "2",
    stockNo: "DJ-8892",
    make: "Nissan",
    model: "X-Trail",
    grade: "S",
    year: 2019,
    mileage_km: 59000,
    engine_cc: 2400,
    transmission: "AT",
    fuel: "Petrol",
    steering: "RHD",
    price_usd: 8500,
    price_local_zmw: 170000,
    currency: "USD",
    location: "Lusaka Yard",
    bodyType: "SUV",
    color: "Black",
    images: ["/cars/car-2.jpg"],
    status: "Reserved",
    vin: "JH4DC...2",
  },
  {
    id: "3",
    stockNo: "DJ-8893",
    make: "Honda",
    model: "Vezel",
    grade: "G",
    year: 2018,
    mileage_km: 72000,
    engine_cc: 1500,
    transmission: "CVT",
    fuel: "Petrol",
    steering: "RHD",
    price_usd: 9000,
    price_local_zmw: 190000,
    currency: "USD",
    location: "Lusaka Yard",
    bodyType: "SUV",
    color: "Silver",
    images: ["/cars/car-3.jpg"],
    status: "Available",
    vin: "JH4DC...3",
    inspectionReportUrl: '/inspection-reports/3.pdf',
  },
  {
    id: "4",
    stockNo: "DJ-8894",
    make: "Toyota",
    model: "Corolla",
    grade: "X",
    year: 2020,
    mileage_km: 45000,
    engine_cc: 1800,
    transmission: "MT",
    fuel: "Petrol",
    steering: "RHD",
    price_usd: 7500,
    price_local_zmw: 150000,
    currency: "USD",
    location: "Lusaka Yard",
    bodyType: "Sedan",
    color: "Blue",
    images: ["/cars/car-1.jpg"],
    status: "Available",
    vin: "JH4DC...4",
  },
  {
    id: "5",
    stockNo: "DJ-8895",
    make: "Mitsubishi",
    model: "Pajero",
    grade: "Exceed",
    year: 2016,
    mileage_km: 120000,
    engine_cc: 3200,
    transmission: "AT",
    fuel: "Diesel",
    steering: "RHD",
    price_usd: 12000,
    price_local_zmw: 250000,
    currency: "USD",
    location: "Lusaka Yard",
    bodyType: "SUV",
    color: "Red",
    images: ["/cars/car-2.jpg"],
    status: "Sold",
    vin: "JH4DC...5",
  },
];

export const featuredCars = [cars[0], cars[2]];

export const testimonials = [
  { id: 't1', name: 'John K', text: 'Great service and fast shipping.' },
  { id: 't2', name: 'Mr. L', text: 'Trusted dealer with clear prices.' },
];

export default { tenantTheme, cars, featuredCars, testimonials };
