#!/usr/bin/env bash
set -euo pipefail

# =============================================================
# Denuel Auto - Frontend Deployment Script for Node.js Server
# =============================================================
# This script deploys the Next.js frontend to a Node.js server
# Prerequisites: Node.js 18+, npm, PM2 (will be installed if missing)
#
# Usage:
#   ./scripts/deploy-frontend-nodejs.sh [options]
#
# Options:
#   --domain DOMAIN       Your domain (e.g., denuelauto.com)
#   --api-url URL         Backend API URL (e.g., https://api.denuelauto.com)
#   --install-deps        Install system dependencies (nginx, certbot)
#   --setup-ssl           Setup SSL with Let's Encrypt
#   --help                Show this help message
# =============================================================

DOMAIN=""
API_URL=""
INSTALL_DEPS=false
SETUP_SSL=false
FRONTEND_DIR="/var/www/denuel/frontend"
FRONTEND_PORT=3000

# Colors for output
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
NC='\033[0m' # No Color

log_info() { echo -e "${GREEN}[INFO]${NC} $1"; }
log_warn() { echo -e "${YELLOW}[WARN]${NC} $1"; }
log_error() { echo -e "${RED}[ERROR]${NC} $1"; }

show_help() {
    head -25 "$0" | tail -20
    exit 0
}

# Parse arguments
while [[ $# -gt 0 ]]; do
    case $1 in
        --domain) DOMAIN="$2"; shift 2 ;;
        --api-url) API_URL="$2"; shift 2 ;;
        --install-deps) INSTALL_DEPS=true; shift ;;
        --setup-ssl) SETUP_SSL=true; shift ;;
        --help) show_help ;;
        *) log_error "Unknown option: $1"; exit 1 ;;
    esac
done

# Prompt for missing required values
if [ -z "$DOMAIN" ]; then
    read -p "Enter your domain (e.g., denuelauto.com): " DOMAIN
fi

if [ -z "$API_URL" ]; then
    read -p "Enter your backend API URL (e.g., https://api.denuelauto.com): " API_URL
fi

log_info "Starting frontend deployment..."
log_info "Domain: $DOMAIN"
log_info "API URL: $API_URL"
log_info "Frontend directory: $FRONTEND_DIR"

# =============================================================
# Step 1: Install system dependencies (optional)
# =============================================================
if [ "$INSTALL_DEPS" = true ]; then
    log_info "Installing system dependencies..."
    sudo apt update
    sudo apt install -y nginx certbot python3-certbot-nginx curl
fi

# =============================================================
# Step 2: Install PM2 if not present
# =============================================================
if ! command -v pm2 &> /dev/null; then
    log_info "Installing PM2..."
    sudo npm install -g pm2
fi

# =============================================================
# Step 3: Create frontend directory and set permissions
# =============================================================
log_info "Setting up frontend directory..."
sudo mkdir -p "$FRONTEND_DIR"
sudo chown -R $(whoami):$(whoami) "$FRONTEND_DIR"

# =============================================================
# Step 4: Copy frontend files (if running from source)
# =============================================================
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
SOURCE_FRONTEND="$(dirname "$SCRIPT_DIR")/frontend"

if [ -d "$SOURCE_FRONTEND" ] && [ "$SOURCE_FRONTEND" != "$FRONTEND_DIR" ]; then
    log_info "Copying frontend source files..."
    rsync -av --exclude='node_modules' --exclude='.next' "$SOURCE_FRONTEND/" "$FRONTEND_DIR/"
fi

cd "$FRONTEND_DIR"

# =============================================================
# Step 5: Create .env.local with API URL
# =============================================================
log_info "Creating .env.local..."
cat > .env.local << EOF
# Generated by deploy-frontend-nodejs.sh on $(date)
NEXT_PUBLIC_API_BASE_URL=$API_URL
NODE_ENV=production
EOF

# =============================================================
# Step 6: Install dependencies and build
# =============================================================
log_info "Installing npm dependencies..."
npm ci

log_info "Building Next.js application..."
npm run build

# Verify _next/static was generated
if [ -d ".next/static" ]; then
    log_info "✓ Build successful - .next/static directory created"
else
    log_error "Build may have failed - .next/static directory not found"
    exit 1
fi

# =============================================================
# Step 7: Start/restart with PM2
# =============================================================
log_info "Starting frontend with PM2..."

# Create PM2 ecosystem file for frontend
cat > ecosystem.frontend.config.js << 'EOF'
module.exports = {
  apps: [{
    name: 'denuel-frontend',
    script: 'npm',
    args: 'start',
    cwd: '/var/www/denuel/frontend',
    instances: 1,
    autorestart: true,
    watch: false,
    max_memory_restart: '512M',
    env: {
      NODE_ENV: 'production',
      PORT: 3000
    }
  }]
};
EOF

# Stop existing instance if running
pm2 delete denuel-frontend 2>/dev/null || true

# Start fresh
pm2 start ecosystem.frontend.config.js
pm2 save

log_info "✓ Frontend running on port $FRONTEND_PORT"

# =============================================================
# Step 8: Configure Nginx
# =============================================================
log_info "Configuring Nginx..."

NGINX_CONF="/etc/nginx/sites-available/$DOMAIN"
sudo tee "$NGINX_CONF" > /dev/null << EOF
# Denuel Auto Frontend - $DOMAIN
# Generated by deploy-frontend-nodejs.sh

server {
    listen 80;
    server_name $DOMAIN www.$DOMAIN;

    # Security headers
    add_header X-Frame-Options SAMEORIGIN;
    add_header X-Content-Type-Options nosniff;
    add_header X-XSS-Protection "1; mode=block";

    # Gzip compression
    gzip on;
    gzip_types text/plain text/css application/json application/javascript text/xml application/xml text/javascript;

    # Proxy to Next.js
    location / {
        proxy_pass http://127.0.0.1:$FRONTEND_PORT;
        proxy_http_version 1.1;
        proxy_set_header Host \$host;
        proxy_set_header X-Real-IP \$remote_addr;
        proxy_set_header X-Forwarded-For \$proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto \$scheme;
        proxy_set_header Upgrade \$http_upgrade;
        proxy_set_header Connection 'upgrade';
        proxy_cache_bypass \$http_upgrade;
    }

    # Cache static assets
    location /_next/static/ {
        proxy_pass http://127.0.0.1:$FRONTEND_PORT;
        proxy_cache_valid 60m;
        add_header Cache-Control "public, max-age=31536000, immutable";
    }

    # Health check
    location /api/health {
        proxy_pass http://127.0.0.1:$FRONTEND_PORT;
    }
}
EOF

# Enable site
sudo ln -sf "$NGINX_CONF" /etc/nginx/sites-enabled/

# Test and reload nginx
sudo nginx -t && sudo systemctl reload nginx
log_info "✓ Nginx configured for $DOMAIN"

# =============================================================
# Step 9: Setup SSL (optional)
# =============================================================
if [ "$SETUP_SSL" = true ]; then
    log_info "Setting up SSL with Let's Encrypt..."
    sudo certbot --nginx -d "$DOMAIN" -d "www.$DOMAIN" --non-interactive --agree-tos --email "admin@$DOMAIN" || {
        log_warn "Certbot failed. You may need to run it manually:"
        echo "  sudo certbot --nginx -d $DOMAIN"
    }
fi

# =============================================================
# Step 10: Setup PM2 startup on boot
# =============================================================
log_info "Configuring PM2 to start on boot..."
pm2 startup systemd -u $(whoami) --hp $HOME 2>/dev/null || true
pm2 save

# =============================================================
# Summary
# =============================================================
echo ""
echo "=============================================="
log_info "Deployment Complete!"
echo "=============================================="
echo ""
echo "Frontend URL: http://$DOMAIN"
echo "PM2 Status:   pm2 status"
echo "PM2 Logs:     pm2 logs denuel-frontend"
echo "Restart:      pm2 restart denuel-frontend"
echo ""
echo "Next steps:"
if [ "$SETUP_SSL" = false ]; then
    echo "  1. Setup SSL: sudo certbot --nginx -d $DOMAIN"
fi
echo "  2. Verify site loads at http://$DOMAIN"
echo "  3. Check /_next/static/ assets are loading"
echo ""

# Verify the build
log_info "Verifying deployment..."
sleep 3
curl -sI "http://127.0.0.1:$FRONTEND_PORT" | head -5 || log_warn "Could not verify frontend is responding"

exit 0
