# =============================================================
# Denuel Auto - Frontend Deployment Script for Node.js Server
# PowerShell version for Windows local preparation
# =============================================================
# This script prepares the frontend for deployment and can upload to server
#
# Usage:
#   .\scripts\deploy-frontend-nodejs.ps1 -Domain "denuelauto.com" -ApiUrl "https://api.denuelauto.com"
# =============================================================

param(
    [Parameter(Mandatory=$true)]
    [string]$Domain,
    
    [Parameter(Mandatory=$true)]
    [string]$ApiUrl,
    
    [string]$ServerHost,
    [string]$ServerUser = "root",
    [string]$ServerPath = "/var/www/denuel",
    [switch]$UploadOnly,
    [switch]$BuildOnly
)

$ErrorActionPreference = "Stop"

Write-Host "======================================" -ForegroundColor Cyan
Write-Host "Denuel Auto Frontend Deployment" -ForegroundColor Cyan
Write-Host "======================================" -ForegroundColor Cyan
Write-Host ""
Write-Host "Domain:  $Domain" -ForegroundColor Green
Write-Host "API URL: $ApiUrl" -ForegroundColor Green
Write-Host ""

# Get paths
$ScriptDir = Split-Path -Parent $MyInvocation.MyCommand.Path
$RootDir = Split-Path -Parent $ScriptDir
$FrontendDir = Join-Path $RootDir "frontend"

if (-not (Test-Path $FrontendDir)) {
    Write-Host "ERROR: Frontend directory not found at $FrontendDir" -ForegroundColor Red
    exit 1
}

Set-Location $FrontendDir

# =============================================================
# Step 1: Create .env.local
# =============================================================
Write-Host "[1/5] Creating .env.local..." -ForegroundColor Yellow

$envContent = @"
# Generated by deploy-frontend-nodejs.ps1 on $(Get-Date)
NEXT_PUBLIC_API_BASE_URL=$ApiUrl
NODE_ENV=production
"@

$envContent | Out-File -FilePath ".env.local" -Encoding UTF8
Write-Host "  Created .env.local with API URL: $ApiUrl" -ForegroundColor Green

# =============================================================
# Step 2: Install dependencies
# =============================================================
Write-Host "[2/5] Installing dependencies..." -ForegroundColor Yellow
npm ci
if ($LASTEXITCODE -ne 0) {
    Write-Host "ERROR: npm ci failed" -ForegroundColor Red
    exit 1
}

# =============================================================
# Step 3: Build the frontend
# =============================================================
Write-Host "[3/5] Building Next.js application..." -ForegroundColor Yellow
npm run build
if ($LASTEXITCODE -ne 0) {
    Write-Host "ERROR: Build failed" -ForegroundColor Red
    exit 1
}

# Verify .next/static was created
$staticDir = Join-Path $FrontendDir ".next\static"
if (Test-Path $staticDir) {
    $staticSize = (Get-ChildItem $staticDir -Recurse | Measure-Object -Property Length -Sum).Sum / 1MB
    Write-Host "  Build successful! .next/static size: $([math]::Round($staticSize, 2)) MB" -ForegroundColor Green
} else {
    Write-Host "ERROR: .next/static directory not created" -ForegroundColor Red
    exit 1
}

if ($BuildOnly) {
    Write-Host ""
    Write-Host "Build complete. Use -UploadOnly to upload to server." -ForegroundColor Cyan
    exit 0
}

# =============================================================
# Step 4: Create deployment package
# =============================================================
Write-Host "[4/5] Creating deployment package..." -ForegroundColor Yellow

$deployDir = Join-Path $RootDir "deploy-package"
$frontendDeployDir = Join-Path $deployDir "frontend"

# Clean and create deploy directory
if (Test-Path $deployDir) { Remove-Item $deployDir -Recurse -Force }
New-Item -ItemType Directory -Path $frontendDeployDir -Force | Out-Null

# Copy required files
$filesToCopy = @(
    ".next",
    "public",
    "package.json",
    "package-lock.json",
    ".env.local",
    "next.config.js"
)

foreach ($file in $filesToCopy) {
    $sourcePath = Join-Path $FrontendDir $file
    if (Test-Path $sourcePath) {
        $destPath = Join-Path $frontendDeployDir $file
        if ((Get-Item $sourcePath) -is [System.IO.DirectoryInfo]) {
            Copy-Item $sourcePath $destPath -Recurse
        } else {
            Copy-Item $sourcePath $destPath
        }
        Write-Host "  Copied: $file" -ForegroundColor Gray
    }
}

# Copy deployment script
Copy-Item (Join-Path $ScriptDir "deploy-frontend-nodejs.sh") $deployDir

# Create PM2 ecosystem file
$ecosystemContent = @"
module.exports = {
  apps: [{
    name: 'denuel-frontend',
    script: 'npm',
    args: 'start',
    cwd: '$ServerPath/frontend',
    instances: 1,
    autorestart: true,
    watch: false,
    max_memory_restart: '512M',
    env: {
      NODE_ENV: 'production',
      PORT: 3000
    }
  }]
};
"@
$ecosystemContent | Out-File -FilePath (Join-Path $frontendDeployDir "ecosystem.config.js") -Encoding UTF8

Write-Host "  Deployment package created at: $deployDir" -ForegroundColor Green

# =============================================================
# Step 5: Upload to server (if credentials provided)
# =============================================================
if ($ServerHost) {
    Write-Host "[5/5] Uploading to server..." -ForegroundColor Yellow
    
    # Check for scp
    if (-not (Get-Command scp -ErrorAction SilentlyContinue)) {
        Write-Host "  scp not found. Please install OpenSSH or use another method to upload:" -ForegroundColor Yellow
        Write-Host "  Upload the contents of $deployDir to $ServerPath on your server" -ForegroundColor Yellow
    } else {
        Write-Host "  Uploading to ${ServerUser}@${ServerHost}:${ServerPath}..." -ForegroundColor Gray
        
        # Upload
        scp -r "$deployDir/*" "${ServerUser}@${ServerHost}:${ServerPath}/"
        
        if ($LASTEXITCODE -eq 0) {
            Write-Host "  Upload complete!" -ForegroundColor Green
            Write-Host ""
            Write-Host "Now SSH into your server and run:" -ForegroundColor Cyan
            Write-Host "  cd $ServerPath" -ForegroundColor White
            Write-Host "  chmod +x deploy-frontend-nodejs.sh" -ForegroundColor White
            Write-Host "  ./deploy-frontend-nodejs.sh --domain $Domain --api-url $ApiUrl" -ForegroundColor White
        } else {
            Write-Host "  Upload failed. Check your SSH credentials." -ForegroundColor Red
        }
    }
} else {
    Write-Host "[5/5] Skipping upload (no server specified)" -ForegroundColor Yellow
    Write-Host ""
    Write-Host "To upload manually:" -ForegroundColor Cyan
    Write-Host "  1. Copy $deployDir to your server at $ServerPath" -ForegroundColor White
    Write-Host "  2. SSH into your server" -ForegroundColor White
    Write-Host "  3. Run: cd $ServerPath && chmod +x deploy-frontend-nodejs.sh" -ForegroundColor White
    Write-Host "  4. Run: ./deploy-frontend-nodejs.sh --domain $Domain --api-url $ApiUrl" -ForegroundColor White
}

# =============================================================
# Summary
# =============================================================
Write-Host ""
Write-Host "======================================" -ForegroundColor Cyan
Write-Host "Deployment Preparation Complete!" -ForegroundColor Green
Write-Host "======================================" -ForegroundColor Cyan
Write-Host ""
Write-Host "Package location: $deployDir" -ForegroundColor White
Write-Host ""
Write-Host "Server commands to run after upload:" -ForegroundColor Yellow
Write-Host "  cd $ServerPath/frontend" -ForegroundColor White
Write-Host "  npm ci --production" -ForegroundColor White
Write-Host "  pm2 start ecosystem.config.js" -ForegroundColor White
Write-Host "  pm2 save" -ForegroundColor White
Write-Host ""
